// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Automatically categorizes uploaded documents using AI.
 *
 * - autoCategorizeDocument - A function that handles the document categorization process.
 * - AutoCategorizeDocumentInput - The input type for the autoCategorizeDocument function.
 * - AutoCategorizeDocumentOutput - The return type for the autoCategorizeDocument function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AutoCategorizeDocumentInputSchema = z.object({
  documentText: z
    .string()
    .describe('The text content extracted from the document.'),
});
export type AutoCategorizeDocumentInput = z.infer<typeof AutoCategorizeDocumentInputSchema>;

const AutoCategorizeDocumentOutputSchema = z.object({
  category: z
    .string()
    .describe(
      'The predicted category of the document.  Options: Medical, Legal, Academic, Financial, Personal, or Other.'
    ),
  confidence: z
    .number()
    .describe(
      'A number between 0 and 1 indicating the confidence level of the categorization.'
    ),
});
export type AutoCategorizeDocumentOutput = z.infer<typeof AutoCategorizeDocumentOutputSchema>;

export async function autoCategorizeDocument(input: AutoCategorizeDocumentInput): Promise<AutoCategorizeDocumentOutput> {
  return autoCategorizeDocumentFlow(input);
}

const prompt = ai.definePrompt({
  name: 'autoCategorizeDocumentPrompt',
  input: {schema: AutoCategorizeDocumentInputSchema},
  output: {schema: AutoCategorizeDocumentOutputSchema},
  prompt: `You are an expert document categorization AI.

  Analyze the text from the document provided, and determine the most appropriate category.  You must respond with only a single word representing the category, and a confidence value as a number between 0 and 1.

  The categories are:
  - Medical
  - Legal
  - Academic
  - Financial
  - Personal
  - Other

  Document Text: {{{documentText}}}`,
});

const autoCategorizeDocumentFlow = ai.defineFlow(
  {
    name: 'autoCategorizeDocumentFlow',
    inputSchema: AutoCategorizeDocumentInputSchema,
    outputSchema: AutoCategorizeDocumentOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
